import { AppError } from "../../../utils/error";

export enum ECS_ERROR {
	EID_MAX_INDEX_OVERFLOW = "EID_MAX_INDEX_OVERFLOW",
	EID_MAX_GEN_OVERFLOW = "EID_MAX_GEN_OVERFLOW",
	COMPONENT_NOT_REGISTERED = "COMPONENT_NOT_REGISTERED",
	COMPONENT_LIMIT_EXCEEDED = "COMPONENT_LIMIT_EXCEEDED",
	ENTITY_NOT_ALIVE = "ENTITY_NOT_ALIVE",
	CIRCULAR_SYSTEM_DEPENDENCY = "CIRCULAR_SYSTEM_DEPENDENCY",
	DUPLICATE_SYSTEM = "DUPLICATE_SYSTEM",
	ARCHETYPE_NOT_FOUND = "ARCHETYPE_NOT_FOUND",
	RESOURCE_NOT_REGISTERED = "RESOURCE_NOT_REGISTERED",
	RESOURCE_ALREADY_REGISTERED = "RESOURCE_ALREADY_REGISTERED",
	EVENT_ALREADY_REGISTERED = "EVENT_ALREADY_REGISTERED",
	EVENT_NOT_REGISTERED = "EVENT_NOT_REGISTERED",
	FIELD_NOT_REGISTERED = "FIELD_NOT_REGISTERED",
	RELATION_NOT_REGISTERED = "RELATION_NOT_REGISTERED",
	RELATION_MODE_INVALID = "RELATION_MODE_INVALID",
	RELATION_MODE_MISMATCH = "RELATION_MODE_MISMATCH",
	RELATION_CYCLE = "RELATION_CYCLE",
	SPARSE_CACHE_KEY_OVERFLOW = "SPARSE_CACHE_KEY_OVERFLOW",
	SPARSE_QUERY_DENSE_PATH = "SPARSE_QUERY_DENSE_PATH",
	HIERARCHY_ALREADY_SET = "HIERARCHY_ALREADY_SET",
	HIERARCHY_INVALID_MAX_DEPTH = "HIERARCHY_INVALID_MAX_DEPTH",
	OBSERVER_NON_CONVERGENT = "OBSERVER_NON_CONVERGENT",
	OBSERVER_INVALID_CONFIG = "OBSERVER_INVALID_CONFIG",
	OBSERVER_ONSET_EMIT = "OBSERVER_ONSET_EMIT",
	INVALID_FIXED_TIMESTEP = "INVALID_FIXED_TIMESTEP",
	INVALID_MAX_FIXED_STEPS = "INVALID_MAX_FIXED_STEPS",
	INVALID_RECORDER_SCHEDULE = "INVALID_RECORDER_SCHEDULE",
	EMPTY_ARCHETYPE_MATERIALIZE = "EMPTY_ARCHETYPE_MATERIALIZE",
	COMPONENT_INDEX_INVARIANT = "COMPONENT_INDEX_INVARIANT",
	OPTIONAL_TERM_NOT_DECLARED = "OPTIONAL_TERM_NOT_DECLARED",
	QUERY_ACCESS_UNDECLARED = "QUERY_ACCESS_UNDECLARED",
	/** A system touched a component/sparse/relation/resource it didn't declare
	 * in its access surface — distinct from *_NOT_REGISTERED (which means the
	 * thing was never registered with the world at all). */
	ACCESS_UNDECLARED = "ACCESS_UNDECLARED",
	SYSTEM_FN_ARITY = "SYSTEM_FN_ARITY",
	PARTITION_APPEND_NEEDS_ENTITY_ROW = "PARTITION_APPEND_NEEDS_ENTITY_ROW",
	PARTITION_BULK_INTO_DISABLED = "PARTITION_BULK_INTO_DISABLED",
	ENTITY_NOT_DISABLED = "ENTITY_NOT_DISABLED",
	BACKEND_ALREADY_ATTACHED = "BACKEND_ALREADY_ATTACHED",
	DETERMINISM_DISABLED = "DETERMINISM_DISABLED",
	NON_DETERMINISTIC_COLUMN_TYPE = "NON_DETERMINISTIC_COLUMN_TYPE",
	INVALID_MEMORY_OPTIONS = "INVALID_MEMORY_OPTIONS",
	STORE_CAP_EXCEEDED = "STORE_CAP_EXCEEDED",
	REGION_NOT_DECLARED = "REGION_NOT_DECLARED",
	COMMAND_LOG_TAG_COLLISION = "COMMAND_LOG_TAG_COLLISION"
}

export class ECSError extends AppError {
	constructor(
		public readonly category: ECS_ERROR,
		message?: string,
		context?: Record<string, unknown>
	) {
		super(message ?? category, true, context);
	}
}

export function isEcsError(error: unknown): error is ECSError {
	return error instanceof ECSError;
}
